theme: jekyll-theme-slate

title: Alexey Sudachen
description: the page of my cyber engineering projects
github:
  repository_url: https://github.com/sudachen

_site:
  title: Alexey Sudachen
  description: the page of my cyber engineering projects
  github:
    repository_url: https://github.com/sudachen
